### ISSUE TITLE
Stuck on Getting Location?

### ISSUE THREAD

**Issue by oleerik** [kyuur/nearbypokemon#1]
Hello!
I've tried the app in 3 browsers (all of which has location access) but it's stuck on Getting Location.
In the firefox app it has loaded successfully once and once only. Is this my fault?

**Comment by oleerik** [comment]
Hm, seems to be working fine on the lightning browser. Strange stuff.

**Comment by kyuur** [comment]
Just for future reference if anyone encounters a similar issue; if you're using my github page itself it should work in any browser as long as location services are on. If you're running this locally or from your own site, geolocation has been deemed 'unsafe' if you're not using HTTPS in some browsers (like Chrome) so you'll need to manually enter your coords or enable the feature manually.

https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
