### ISSUE TITLE
New features welcome?

### ISSUE THREAD

**Issue by oleerik** [kyuur/nearbypokemon#2]
Hey!

Are new features welcome? (For instance a clock to show how long a spawn has left or notifications when finding rarer pokemon?)
I get that this is supposed to be as close to the real deal as possible so I totally get it if you do not want new features :)

**Comment by kyuur** [comment]
As you've said, for my branch I prefer to keep it as close to the app tracker as possible. That being said there is some stuff like to implement, namely:

a) A way to dismiss Pokemon you've caught in the app
b) A way to track a particular Pokemon (like if you click on one in the app)

Both of these require a slight change to the pokevision api (right now it does not grab the ID from json) that I will upload shortly.

Feel free to fork this and customize it though!

**Comment by oleerik** [comment]
Awesome! I've forked and added the countdown for despawn. I love your ideas though!
